L1_GRAMMARERROR = {
    'Arabic': ['IS_THERE_ANY_NNS', 'SHOULD BE ACITVE VOICE', 'COUPLE_OF_TIMES', 'MISSING PREPOSITION', 'ARTICLE NOUN AGREEMENT', 'MISSING VERB', 'SHOULD BE PLURAL', 'MISSING SUBJECT', 'ALL_MOST_SOME_OF_NOUN', 'DETERMINER NOUN AGREEMENT'],
    'French': ['LETS_DONT', 'COUPLE_OF_TIMES', 'REDUNDANT VERB IN QUESTION', 'HAVE_HAVING', 'IS_THERE_ANY_NNS', 'EACH_EVERY_WITH_SINGULAR_NOUN', 'ADMIT_ENJOY_VB', 'MISSING PREPOSITION', 'MISSING VERB', 'ACCORDING_TO_ME'],
    'German': ['SHOULD BE ACITVE VOICE', 'COUPLE_OF_TIMES', 'HAVE_HAVING', 'ADMIT_ENJOY_VB', 'MISSING PREPOSITION', 'WRONG VERB WITH AUXILIARY VERB', 'IRREGULAR_PAST', 'MUCH_COUNTABLE', 'SHOULD BE ADVERB', 'ADVISE_VBG'],
    'Italian': ['IF_OR_NOT', 'COUPLE_OF_TIMES', 'IS_THERE_ANY_NNS', 'FIRSTLY_OF_ALL', 'EITHER_OF_THE_NN', 'ADMIT_ENJOY_VB', 'EACH_EVERY_WITH_SINGULAR_NOUN', 'SHOULD BE PLURAL', 'MISSING VERB', 'NOT_NEVER'],
    'Japanese': ['NON_ACTION_CONTINUOUS', 'NOUN_ADJECTIVE', 'CAN_ABLE_TO', 'SHOULD BE PLURAL', 'MISSING PREPOSITION', 'ADMIT_ENJOY_VB', 'ALL_MOST_SOME_OF_NOUN', 'MANY_KINDS_OF', 'MISSING ARTICLE', 'MISSING OBJECT PRONOUN'],
    'Chinese-Mandarin': ['DO_ANYONE', 'THANK_IN_ADVANCE', 'SUBJECT VERB AGREEMENT', 'KIND_REGARD', 'MISSING SUBJECT', 'ARTICLE NOUN AGREEMENT', 'WRONG PAST PARTICLE', 'DETERMINER NOUN AGREEMENT', 'THERE_IS_A_LOT_OF', 'SHOULD BE ACTIVE VOICE'],
    'Portuguese': ['MISSING PREPOSITION', 'MISSING SUBJECT', 'ADMIT_ENJOY_VB', 'REDUNDANT AUXILIARY VERB', 'SHOULD BE PLURAL', 'ALLOW_TO', 'KIND_REGARD', 'PHRASE_REPETITION', 'DOUBLE_NEGATIVE', 'THERE_IS_A_LOT_OF'],
    'Russian': ['REDUNDANT VERB IN QUESTION', 'ARTICLE NOUN AGREEMENT', 'WfRONG PREPOSITION', 'SUBJECT VERB AGREEMENT', 'MISSING VERB', 'MISSING SUBJECT', 'ALLOW_TO', 'MISSING PREPOSITION', 'REDUNDANT VERB', 'REDUNDANT PREPOSITION'],
    'Spanish': ['LETS_DONT', 'EITHER_OF_THE_NN', 'ARTICLE NOUN AGREEMENT', 'MISSING SUBJECT', 'MISSING PREPOSITION', 'WRONG VERB WITH AUXILIARY VERB', 'SHOULD BE PLURAL', 'ALL_MOST_SOME_OF_NOUN', 'REDUNDANT VERB', 'ARTICLE IN UNCOUNTABLE'],
    'Turkish': ['AFFECTS', 'ACCORDING_TO_ME', 'SHOULD BE PLURAL', 'MISSING PREPOSITION', 'ALLOW_TO', 'MISSING SUBJECT', 'SHOULD BE SINGULAR', 'ALL_MOST_SOME_OF_NOUN', 'DETERMINER NOUN AGREEMENT', 'REDUNDANT ADVERB'],
}



# Extracted top 0.1%
DIALECT_FEATURE_LIST = [
    'Like as a focussing device',
    'Use of definite article where StE has indefinite article',
    'Use of definite article where StE favours zero',
    'Sentence-initial focus marker',
    'Associative plural marked by postposed and them/them all/dem',
    'Plural forms of interrogative pronouns: using additional elements',
    'New quasi-modals: aspectual meanings',
    'Other possibilities for fronting than StE',
    'Multiple negation / negative concord',
    'Epistemic mustn’t',
    'Other adverbs have the same form as adjectives',
    'No inversion/no auxiliaries in wh-questions',
    'Omission of StE prepositions',
    'Levelling of past tense/past participle verb forms: unmarked forms',
    'Distinctive forms for auxiliary vs. full verb meanings of primary verbs',
    'Invariant be with non-habitual function',
    'Clause-final but = ʼreallyʼ',
    'Double comparatives and superlatives',
    'Wider range of uses of progressive be + V-ing than in StE: extension to stative verbs',
    'Gapping/zero-relativization in subject position',
    'Invariant present tense forms due to generalization of 3rd person –s to all persons',
    'Specialized plural markers for pronouns',
    'Existential / presentational there’s/there is/there was with plural subjects',
    'Use of us + NP in subject function',
    'Regularized comparison strategies: extension of analytic marking',
    'Agreement sensitive to subject type',
    'Absence of plural marking only after quantifiers',
    'Levelling of past tense/past participle verb forms: past participle replacing the past tense form',
    'Absolute use of reflexives',
    'Ain’t as the negated form of be',
    'Benefactive “personal dative” construction',
    'Forms or phrases for the second person plural pronoun other than you',
    'Affirmative anymore ‘nowadays’',
    'Double modals',
    'Other options for clefting than StE',
    'New quasi-modals: core modal meanings',
    'Degree modifier adverbs have the same form as adjectives',
    'There with past participle in resultative contexts',
    'Inverted word order in indirect questions',
    'Unsplit for to in infinitival purpose clauses',
    'Clause-final but = ʼthoughʼ',
    'Levelling of the difference between present perfect and simple past: simple past for StE present perfect',
    'Want/need + past participle',
    'Loosening of sequence of tenses rule',
]
