L1_GRAMMARERROR = {
    'Arabic': ['IS_THERE_ANY_NNS', 'SHOULD BE ACITVE VOICE', 'COUPLE_OF_TIMES', 'MISSING PREPOSITION', 'ARTICLE NOUN AGREEMENT', 'MISSING VERB', 'SHOULD BE PLURAL', 'MISSING SUBJECT', 'ALL_MOST_SOME_OF_NOUN', 'DETERMINER NOUN AGREEMENT'],
    'French': ['LETS_DONT', 'COUPLE_OF_TIMES', 'REDUNDANT VERB IN QUESTION', 'HAVE_HAVING', 'IS_THERE_ANY_NNS', 'EACH_EVERY_WITH_SINGULAR_NOUN', 'ADMIT_ENJOY_VB', 'MISSING PREPOSITION', 'MISSING VERB', 'ACCORDING_TO_ME'],
    'German': ['SHOULD BE ACITVE VOICE', 'COUPLE_OF_TIMES', 'HAVE_HAVING', 'ADMIT_ENJOY_VB', 'MISSING PREPOSITION', 'WRONG VERB WITH AUXILIARY VERB', 'IRREGULAR_PAST', 'MUCH_COUNTABLE', 'SHOULD BE ADVERB', 'ADVISE_VBG'],
    'Italian': ['IF_OR_NOT', 'COUPLE_OF_TIMES', 'IS_THERE_ANY_NNS', 'FIRSTLY_OF_ALL', 'EITHER_OF_THE_NN', 'ADMIT_ENJOY_VB', 'EACH_EVERY_WITH_SINGULAR_NOUN', 'SHOULD BE PLURAL', 'MISSING VERB', 'NOT_NEVER'],
    'Japanese': ['NON_ACTION_CONTINUOUS', 'NOUN_ADJECTIVE', 'CAN_ABLE_TO', 'SHOULD BE PLURAL', 'MISSING PREPOSITION', 'ADMIT_ENJOY_VB', 'ALL_MOST_SOME_OF_NOUN', 'MANY_KINDS_OF', 'MISSING ARTICLE', 'MISSING OBJECT PRONOUN'],
    'Chinese-Mandarin': ['DO_ANYONE', 'THANK_IN_ADVANCE', 'SUBJECT VERB AGREEMENT', 'KIND_REGARD', 'MISSING SUBJECT', 'ARTICLE NOUN AGREEMENT', 'WRONG PAST PARTICLE', 'DETERMINER NOUN AGREEMENT', 'THERE_IS_A_LOT_OF', 'SHOULD BE ACTIVE VOICE'],
    'Portuguese': ['MISSING PREPOSITION', 'MISSING SUBJECT', 'ADMIT_ENJOY_VB', 'REDUNDANT AUXILIARY VERB', 'SHOULD BE PLURAL', 'ALLOW_TO', 'KIND_REGARD', 'PHRASE_REPETITION', 'DOUBLE_NEGATIVE', 'THERE_IS_A_LOT_OF'],
    'Russian': ['REDUNDANT VERB IN QUESTION', 'ARTICLE NOUN AGREEMENT', 'WfRONG PREPOSITION', 'SUBJECT VERB AGREEMENT', 'MISSING VERB', 'MISSING SUBJECT', 'ALLOW_TO', 'MISSING PREPOSITION', 'REDUNDANT VERB', 'REDUNDANT PREPOSITION'],
    'Spanish': ['LETS_DONT', 'EITHER_OF_THE_NN', 'ARTICLE NOUN AGREEMENT', 'MISSING SUBJECT', 'MISSING PREPOSITION', 'WRONG VERB WITH AUXILIARY VERB', 'SHOULD BE PLURAL', 'ALL_MOST_SOME_OF_NOUN', 'REDUNDANT VERB', 'ARTICLE IN UNCOUNTABLE'],
    'Turkish': ['AFFECTS', 'ACCORDING_TO_ME', 'SHOULD BE PLURAL', 'MISSING PREPOSITION', 'ALLOW_TO', 'MISSING SUBJECT', 'SHOULD BE SINGULAR', 'ALL_MOST_SOME_OF_NOUN', 'DETERMINER NOUN AGREEMENT', 'REDUNDANT ADVERB'],
}



# Extracted top 0.1%
DIALECT_FEATURE_LIST = [
    'Like as a focussing device',
    'Use of definite article where StE has indefinite article',
    'Use of definite article where StE favours zero',
    'Sentence-initial focus marker',
    'Associative plural marked by postposed and them/them all/dem',
    'Plural forms of interrogative pronouns: using additional elements',
    'New quasi-modals: aspectual meanings',
    'Other possibilities for fronting than StE',
    'Multiple negation / negative concord',
    'Epistemic mustn’t',
    'Other adverbs have the same form as adjectives',
    'No inversion/no auxiliaries in wh-questions',
    'Omission of StE prepositions',
    'Levelling of past tense/past participle verb forms: unmarked forms',
    'Distinctive forms for auxiliary vs. full verb meanings of primary verbs',
    'Invariant be with non-habitual function',
    'Clause-final but = ʼreallyʼ',
    'Double comparatives and superlatives',
    'Wider range of uses of progressive be + V-ing than in StE: extension to stative verbs',
    'Gapping/zero-relativization in subject position',
    'Invariant present tense forms due to generalization of 3rd person –s to all persons',
    'Specialized plural markers for pronouns',
    'Existential / presentational there’s/there is/there was with plural subjects',
    'Use of us + NP in subject function',
    'Regularized comparison strategies: extension of analytic marking',
    'Agreement sensitive to subject type',
    'Absence of plural marking only after quantifiers',
    'Levelling of past tense/past participle verb forms: past participle replacing the past tense form',
    'Absolute use of reflexives',
    'Ain’t as the negated form of be',
    'Benefactive “personal dative” construction',
    'Forms or phrases for the second person plural pronoun other than you',
    'Affirmative anymore ‘nowadays’',
    'Double modals',
    'Other options for clefting than StE',
    'New quasi-modals: core modal meanings',
    'Degree modifier adverbs have the same form as adjectives',
    'There with past participle in resultative contexts',
    'Inverted word order in indirect questions',
    'Unsplit for to in infinitival purpose clauses',
    'Clause-final but = ʼthoughʼ',
    'Levelling of the difference between present perfect and simple past: simple past for StE present perfect',
    'Want/need + past participle',
    'Loosening of sequence of tenses rule',
]



CEFR_ERROR = {
    'A': [
        'Can end a reported question clause and a relative clause with a preposition, where the preposition is stranded from its complement. ► Clauses: relative',
        'Can form complex noun phrases by using adjective phrases as postmodifiers to give more information about the noun.',
        "Can form complex noun phrases with noun phrase + 'of' + noun phrase + possessive determiner ''s' + noun phrase.",
        "Can introduce a new subject before the '-ing' form (using noun or object pronoun).",
        'Can modify an increasing range of adverbs with other adverbs.► adverbs and adverb phrases: types and meanings',
        "Can use ''s' after a noun phrase with of to indicate possession.",
        "Can use 'It' + 'be' + noun + 'that' clause for focus.",
        "Can use 'can be' to talk about general truths and tendencies.",
        "Can use 'plus' to connect clauses and sentences, often to point out a positive addition or advantage.",
        "Can use 'these ones', 'those ones' as a substitute for plural countable nouns which have already been mentioned or are obvious from the context.",
        "Can use a non-finite subordinate clause with an '-ed' form, before a main clause, for focus, often in formal, academic or business contexts.",
        'Can use a wide range of complex prepositions.',
        'Can use adjective phrases attributively, before a noun.',
        'Can use adjective phrases to modify nouns.',
        'Can use an adverb between the verb and the preposition.',
        "Can use defining relative clauses and non-defining relative clauses ending in a preposition, with 'who/which/that' as the complement of the preposition.",
        'Can use fixed expressions in the front position for focus.',
        'Can use less frequent simple prepositions, often in a more formal, literary or business context.',
        'Can use phrasal verbs + nouns as object + particle.',
        "Can use the '–ed' form of a verb as an adjective, after a noun.",
        'Can use the affirmative forms with a range of pronouns and nouns and an increasing range of verbs.',
        "Can use the passive with 'it' as a dummy subject, to summarise or evaluate in discussions, usually in formal or academic writing.",
        "Can use the past simple with 'did' for emphasis.",
        'Can use the present continuous with verbs that are not usually used in this form to make statements and requests sound less direct.'
    ],
    'B': [
        "Can use 'It' + 'be' + noun + 'that' clause for focus.",
        "Can use 'each' (+ noun or pronoun) as subject followed by 'the other(s)' as object , to refer to two related things. ► pronouns: quantity",
        "Can use 'may well' to give emphasis to something unexpected.",
        "Can use 'not necessarily' to express a possible exception to a general perception, i.e. not in every case.",
        "Can use 'shall' in the main clause after an 'if-' clause  ► conditionals",
        "Can use 'that' and 'those' to convey emotional distance, often to express disapproval.",
        "Can use a non-finite subordinate clause with an '-ed' form, before a main clause, to give focus.",
        'Can use fixed expressions in the front position for focus.',
        'Can use question forms to ask rhetorical questions.',
        "Can use the '–ed' form of a verb as an adjective, after a noun.",
        'Can use the negative question form as a persuasion strategy.',
        "Can use the past simple with 'did' for emphasis.",
        "Can use the possessive pronouns 'hers', 'theirs' and 'his' after noun + 'of'.",
        'Can use the present continuous with verbs that are not usually used in this form to make statements and requests sound less direct.',
        'Can use verb + particle + preposition, where the preposition is separated from its complement. ► Prepositions'
    ]
}
